2024-12-28 18:07:21 - System - __name__ - INFO - Running in standard mode
2024-12-28 18:07:21 - System - __name__ - INFO - Starting the application.
2024-12-28 18:07:21 - System - __name__ - INFO - Connected to database at user_credentials.db
2024-12-28 18:07:21 - System - __name__ - INFO - Services initialized successfully.
2024-12-28 18:07:23 - System - __name__ - ERROR - An unexpected error occurred: name 'usermodel' is not defined
2024-12-28 18:07:23 - System - __name__ - DEBUG - Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Documents\GitHub\Shiva\main.py", line 103, in main
    logger.username = usermodel.username
NameError: name 'usermodel' is not defined

2024-12-28 18:07:27 - System - __name__ - INFO - Database connection closed.
